name: Windows MinGW build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        install: mingw-w64-i686-gcc mingw-w64-i686-make subversion

    - name: prepare datafiles
      run: |
        svn export svn://mutantstargoat.com/datadirs/deeprunner data

    - name: build
      run: mingw32-make

    - uses: actions/upload-artifact@v3
      with:
        name: game-win32
        path: |
          data/
          game.exe

# vi:ts=2 sts=2 sw=2:expandtab
